development:
  adapter: postgresql
  database: reddit_development
  host: localhost
  username: Meredan

test: &TEST
  adapter: postgresql
  database: reddit_test
  host: localhost
  username: Meredan
